Vamos a analizar las licitaciones de Paraguay, del 2013 a julio 2026. Para eso usaremos el primer dataset que contiene los datos de los ítem adjudicados y el segundo que contiene la lista de las empresas adjudicadas.

In [2]:
import pandas as pd
#Aquí cargo el archivo que contiene todas las adjudicaciones.
#Hay una fila por cada ítem adjudicado, no por cada licitación.
#Eso nos permite después matchear con todas las empresas que fueron adjudicadas.
df = pd.read_csv('awards.csv')
df.head()

,compiledRelease/id,compiledRelease/awards/0/id,compiledRelease/awards/0/status,compiledRelease/awards/0/statusDetails,compiledRelease/awards/0/date,compiledRelease/awards/0/value/amount,compiledRelease/awards/0/value/currency,compiledRelease/awards/0/invitationID,compiledRelease/awards/0/buyer/id,compiledRelease/awards/0/buyer/name,compiledRelease/awards/0/relatedBids
0,1f0d1d12-ccfc-6c4c-9c62-41c7ee44905d-1769766812,1f0ebec1-ec7a-6432-baa3-fd36df959c47,active,publicado,2026-01-05T00:00:00-04:00,328000000,PYG,NaN,NaN,NaN,NaN
1,1f0cad77-c31f-6c66-97f4-3dc22c4b8285-1768906397,1f0e58f8-5eaa-69b0-af3a-1f78ddd9d6ae,active,publicado,2025-12-30T00:00:00-04:00,42900000,PYG,NaN,NaN,NaN,NaN
2,1f0922d2-cbe3-6f74-8667-4b6c2cf7d4ab-1767951642,1f0c615e-99f8-6a6e-99ff-69708a588eab,active,publicado,2025-11-20T00:00:00-04:00,60000000,PYG,NaN,NaN,NaN,NaN
3,ocds-03ad3f-466167-1-2026-01-13T10:08:27-04:00,1f0a8fa9-1c41-64be-804d-f51d0c37709c,active,publicado,2025-10-09T00:00:00-04:00,100000000,PYG,NaN,NaN,NaN,NaN
4,389393-construccion-reparacion-instituciones-e...,389393-alfredo-bernardino-lezcano-sanchez-1,active,Adjudicado,2021-08-26T12:00:00-04:00,1339037790,PYG,NaN,NaN,NaN,NaN

In [3]:
#Aquí subimos el segundo dataset que se trata de las empresas adjudicadas
df_proveedores = pd.read_csv('awa_suppliers.csv')
df_proveedores.head()

,compiledRelease/id,compiledRelease/awards/0/id,compiledRelease/awards/0/suppliers/0/id,compiledRelease/awards/0/suppliers/0/name
0,1f0d1d12-ccfc-6c4c-9c62-41c7ee44905d-1769766812,1f0ebec1-ec7a-6432-baa3-fd36df959c47,PY-RUC-80087223-1,SERMED SOCIEDAD ANÓNIMA
1,1f0cad77-c31f-6c66-97f4-3dc22c4b8285-1768906397,1f0e58f8-5eaa-69b0-af3a-1f78ddd9d6ae,PY-RUC-5041806-8,FERNANDO ARIEL ESPINOLA CAÑIZA
2,1f0922d2-cbe3-6f74-8667-4b6c2cf7d4ab-1767951642,1f0c615e-99f8-6a6e-99ff-69708a588eab,PY-RUC-644744-9,CESAR MOSTAFA OCAMPOS
3,ocds-03ad3f-466167-1-2026-01-13T10:08:27-04:00,1f0a8fa9-1c41-64be-804d-f51d0c37709c,PY-RUC-80008802-6,AMBIPAR ENVIRONMENT PARAGUAY S.A.
4,389393-construccion-reparacion-instituciones-e...,389393-alfredo-bernardino-lezcano-sanchez-1,PY-RUC-618172-4,ALFREDO BERNARDINO LEZCANO SANCHEZ

In [4]:
#Ahora vamos a juntarlas
df_completo = pd.merge(
    df,                     
    df_proveedores,         
    on=['compiledRelease/id', 'compiledRelease/awards/0/id'],  
    how='left'       
)

In [5]:
df_completo.sample(5)

,compiledRelease/id,compiledRelease/awards/0/id,compiledRelease/awards/0/status,compiledRelease/awards/0/statusDetails,compiledRelease/awards/0/date,compiledRelease/awards/0/value/amount,compiledRelease/awards/0/value/currency,compiledRelease/awards/0/invitationID,compiledRelease/awards/0/buyer/id,compiledRelease/awards/0/buyer/name,compiledRelease/awards/0/relatedBids,compiledRelease/awards/0/suppliers/0/id,compiledRelease/awards/0/suppliers/0/name
18834,ocds-03ad3f-415212-2026-05-27T15:25:49-04:00,1373-2024-45,closed,cerrada,2024-06-26T15:16:57-04:00,14796000,PYG,NaN,DNCP-SICP-CODE-1373,Facultad de Ciencias Quimicas / Universidad Na...,NaN,PY-RUC-1420732-0,DIANA LORENA CABELLO ORTUZAR
18401,ocds-03ad3f-415212-2026-05-27T15:25:49-04:00,28257,active,Confirmado Orden de Compra,2023-11-29T10:47:15-04:00,11031400,PYG,NaN,DNCP-SICP-CODE-305,Ministerio de Economía y Finanzas,NaN,PY-RUC-80014897-5,SERVI TRAVEL S.A.
21404,ocds-03ad3f-415212-2026-05-27T15:25:49-04:00,1969-2025-42,active,confirmada,2025-11-12T17:44:49-04:00,4748656,PYG,NaN,DNCP-SICP-CODE-226,Universidad Nacional de Asunción (UNA),NaN,PY-RUC-80002827-9,COMPAÑIA MARITIMA PARAGUAYA S.A.
24194,ocds-03ad3f-382392-2026-05-28T08:00:07-04:00,1360-2025-155,active,confirmada,2025-11-10T12:39:41-04:00,17270000,PYG,NaN,DNCP-SICP-CODE-1360,Facultad de Ciencias Medicas / Universidad Nac...,NaN,PY-RUC-80034769-2,YUTY SOCIEDAD ANONIMA
4855,416984-lpn-sbe-104-22-adquisicion-medicamentos...,416984-laboratorios-as-farm-21,active,Adjudicado,2023-03-29T12:00:00-04:00,2265119680,PYG,NaN,NaN,NaN,NaN,PY-RUC-80002442-7,LABORATORIOS AS FARM

In [6]:
#Aquí vemos el resultado de las filas
filas_df = len(df)
filas_proveedores = len(df_proveedores)
filas_coincidencias = len(df_completo)

print(f"Filas en df: {filas_df}")
print(f"Filas en df_proveedores: {filas_proveedores}")
print(f"Filas en df_coincidencias: {filas_coincidencias}")

Filas en df: 27998
Filas en df_proveedores: 28131
Filas en df_coincidencias: 28131

In [ ]:
#Ahora creamos una columna de año
#Primero pasamos la columna date a datetime y luego extraemos el año
fecha_convertida = pd.to_datetime(df_completo['compiledRelease/awards/0/date'], errors='coerce')
df_completo['year'] = fecha_convertida.dt.year

#Limpiamos el número para que no tenga comas y vemos el resultado
df_completo['year'] = df_completo['year'].fillna(0).astype('int64')
print(df_completo[['compiledRelease/awards/0/date', 'year']].head())

  compiledRelease/awards/0/date  year
0     2026-01-05T00:00:00-04:00  2026
1     2025-12-30T00:00:00-04:00  2025
2     2025-11-20T00:00:00-04:00  2025
3     2025-10-09T00:00:00-04:00  2025
4     2021-08-26T12:00:00-04:00  2021

In [9]:
df_completo.columns

Index(['compiledRelease/id', 'compiledRelease/awards/0/id',
       'compiledRelease/awards/0/status',
       'compiledRelease/awards/0/statusDetails',
       'compiledRelease/awards/0/date',
       'compiledRelease/awards/0/value/amount',
       'compiledRelease/awards/0/value/currency',
       'compiledRelease/awards/0/invitationID',
       'compiledRelease/awards/0/buyer/id',
       'compiledRelease/awards/0/buyer/name',
       'compiledRelease/awards/0/relatedBids',
       'compiledRelease/awards/0/suppliers/0/id',
       'compiledRelease/awards/0/suppliers/0/name', 'year'],
      dtype='str')

In [11]:
#Simplificamos las columnas
columnas_nuevas = {
    'compiledRelease/id': 'id_licitacion_global',
    'compiledRelease/awards/0/id': 'id_adjudicacion_contrato',
    'compiledRelease/awards/0/status': 'estado_adjudicacion',
    'compiledRelease/awards/0/statusDetails': 'detalles_estado',
    'compiledRelease/awards/0/date': 'fecha_adjudicacion_original',
    'compiledRelease/awards/0/value/amount': 'monto_adjudicado',
    'compiledRelease/awards/0/value/currency': 'moneda',
    'compiledRelease/awards/0/invitationID': 'id_invitacion',
    'compiledRelease/awards/0/buyer/id': 'id_institucion_compradora',
    'compiledRelease/awards/0/buyer/name': 'nombre_institucion',
    'compiledRelease/awards/0/relatedBids': 'ofertas_relacionadas_ids',
    'compiledRelease/awards/0/suppliers/0/id': 'ruc_proveedor',
    'compiledRelease/awards/0/suppliers/0/name': 'nombre_proveedor',
    'year': 'anho_adjudicacion'
}

#Renombramos las columnas manteniendo todo el dataset intacto
df_completo_renombrado = df_completo.rename(columns=columnas_nuevas)

# manejamos los casillas vacías
df_completo_renombrado['nombre_institucion'] = df_completo_renombrado['nombre_institucion'].fillna('No especificada')
df_completo_renombrado['anho_adjudicacion'] = df_completo_renombrado['anho_adjudicacion'].fillna(0).astype('int64')

In [12]:
df_completo_renombrado.columns

Index(['id_licitacion_global', 'id_adjudicacion_contrato',
       'estado_adjudicacion', 'detalles_estado', 'fecha_adjudicacion_original',
       'monto_adjudicado', 'moneda', 'id_invitacion',
       'id_institucion_compradora', 'nombre_institucion',
       'ofertas_relacionadas_ids', 'ruc_proveedor', 'nombre_proveedor',
       'anho_adjudicacion'],
      dtype='str')

In [ ]:
#Guardamos el archivo
df_completo_renombrado.to_csv('datos_web_limpios.csv', index=False)